package com.nathan.tibiastats.domain.model;

public enum StatCategory {
    ACHIEVEMENTS,
    AXE_FIGHTING,
    BOSS_POINTS,
    BOUNTY_POINTS_EARNED,
    CHARM_POINTS,
    CLUB_FIGHTING,
    DISTANCE_FIGHTING,
    DROME_SCORE,
    EXPERIENCE,
    FISHING,
    FIST_FIGHTING,
    GOSHNARS_TAINT,
    LOYALTY_POINTS,
    MAGIC_LEVEL,
    SHIELDING,
    SWORD_FIGHTING,
    WEEKLY_TASKS_COMPLETED
}
