package com.nathan.tibiastats.domain.model;

public enum StatCategory {
    ACHIEVEMENTS, AXE_FIGHTING, CHARM_POINTS, CLUB_FIGHTING, DISTANCE_FIGHTING,
    EXPERIENCE, FISHING, FIST_FIGHTING, GOSHNARS_TAINT, LOYALTY_POINTS,
    MAGIC_LEVEL, SHIELDING, SWORD_FIGHTING, DROME_SCORE, BOSS_POINTS
}