spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tibiastats
    username: tibia
    password: secret
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "please-change-me-to-a-very-long-random-secret"
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  task:
    scheduling:
      pool:
        size: 4

  graphql:
    path: /graphql.

server:
  port: 8080

# Scraping schedules (overrideable)
tibiastats:
  scrape:
    worlds:
      enabled: true
      rate-ms: 60000
    character-details:
      enabled: true
      rate-ms: 60000
      initial-delay-ms: 15000
      batch-size: 50

    guilds:
      enabled: false
      rate-ms: 3600000          # 1h
      initial-delay-ms: 30000
      world-limit: 0
      guild-limit: 50
      page-delay-ms: 750
      list-enabled: true
      details-enabled: true
    highscores:
      enabled: true
      cron: "0 0 7 * * *"
      categories: "ACHIEVEMENTS,AXE_FIGHTING,BOSS_POINTS,BOUNTY_POINTS_EARNED,CHARM_POINTS,CLUB_FIGHTING,DISTANCE_FIGHTING,DROME_SCORE,EXPERIENCE,FISHING,FIST_FIGHTING,GOSHNARS_TAINT,LOYALTY_POINTS,MAGIC_LEVEL,SHIELDING,SWORD_FIGHTING,WEEKLY_TASKS_COMPLETED"
      vocations: "0,1,2,3,4,5,6"
      max-pages: 100
      page-delay-ms: 1000
      world-limit: 0
  jwt:
    access-ttl-ms: 900000
    refresh-ttl-ms: 1209600000
